### ISSUE TITLE
Support more PostCSS options

### ISSUE THREAD

**Issue by Grawl** [tureki/laravel-elixir-postcss#7]
At least I want to have [this options](https://github.com/postcss/postcss#options):
- `syntax`: an object providing a syntax parser and a stringifier – for example, [sugar](https://github.com/postcss/sugarss).
- `parser`: a special syntax parser (for example, [SCSS]).
- `stringifier`: a special syntax output generator (for example, [Midas]).
- `map`: [source map options].

**Comment by tureki** [comment]
It will be supported in future release.

You can modify the code and pull request If you have any idea or proposal. 👍

**Comment by 7ammer** [comment]
Any news on this feature?
Thanks :)

**Comment by tureki** [comment]
Hi @7ammer,

There is no a clear time to add these features now. Orz!

**Comment by tureki** [comment]
Hi guys, I have already supported this feature on version [0.5.0](https://github.com/tureki/laravel-elixir-postcss/releases/tag/v0.5.0) 😄 

Detail: [README](https://github.com/tureki/laravel-elixir-postcss/blob/v0.5.0/README.md)
